- include_vars: vars.yml

- name: Add Postgresql repository key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    
- name: Add Postgresql repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    state: present
    
- name: Install Postgresql-15
  apt:
    name: postgresql-15
    state: present
    update_cache: yes

- name: Install pytho3
  apt:
    name: python3-pip
    state: present

- name: Install Python packages
  pip:
    name: psycopg2-binary
    state: present 
- name: Install acl packages
  apt:
    name: acl
    state: present

- name: Create db user
  postgresql_user:
    state: present
    name: "{{ db_user }}"
    password: " {{ db_password }}"
  become: true
  become_user: postgres
    
- name: Create db
  postgresql_db:
    state: present
    name: "{{ db_name }}"
  become: yes
  become_user: postgres
    
- name: Access db for user
  postgresql_privs:
    type: database
    database: "{{ db_name }}"
    role: "{{ db_user }}"
    grant_option: no
    privs: all
  become: yes
  become_user: postgres
