---

- name: create directory patroni in /etc
  file:
    state: directory
    dest: /etc/patroni

- name: Install python3
  apt:
    name: python3-pip
    state: present

- name: install patroni and etcd
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - psycopg2-binary
    - patroni
    - python-etcd
    

- name: create directory postgresql
  file:
    state: directory
    dest: /data_db/patroni
    owner: postgres
    group: postgres
    mode: "0700"

- name: Put patroni config file
  template:
    src: templates/patroni.yml.j2
    dest: /etc/patroni/patroni.yml
    owner: postgres
    group: postgres
    mode: "0640"

- name: Create service patroni
  template:
    src: templates/patroni.service.j2
    dest: /etc/systemd/system/patroni.service

- name: Sevice enable  and start patroni
  systemd:
    name: patroni
    state: restarted
    enabled: true
