---

- name: Install etcd
  apt:
    name: etcd
    state: present

- name: Create directory for data (etcd)
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: etcd
    group: etcd
    mode: "0700"

- name: Create conf file in /etc/default/etcd
  template:
    src: templates/etcd.conf.j2
    dest: /etc/default/etcd

- name: restart etcd
  systemd_service:
    daemon_reload: true
    name: etcd
    state: restarted
    enabled: true
